export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODALE = 'CLOSE_MODALE';

export const OPEN_FILE_MODALE = 'OPEN_FILE_MODALE';
export const CLOSE_FILE_MODALE = 'CLOSE_FILE_MODALE';

export const OPEN_CHOOS_MODAL = 'OPEN_CHOOS_MODAL';
export const CLOSE_CHOOS_MODALE = 'CLOSE_CHOOS_MODALE';

export const OPEN_START_MODAL = 'OPEN_START_MODAL';

export const START_PROJECT = 'START_PROJECT';
export const ADD_FOLDER = "ADD_FOLDER";
export const ADD_FOLDER_CHILD = 'ADD_FOLDER_CHILD'
export const ADD_FILL = 'ADD_FILL';
export const ADD_NEW_FILL = 'ADD_NEW_FILL';
export const SHOW_DATELS_FOLDER = 'SHOW_DATELS_FOLDER';

export const DELETE_FILE_OR_FOLDER = 'DELETE_FILE_OR_FOLDER';
export const REMOVE_FILE_OR_FOLDER = 'REMOVE_FILE_OR_FOLDER';
export const CANCEL_REMOVE = 'CANCEL_REMOVE';

export const SHOW_DETAILS_FOLDER = 'SHOW_DETAILS_FOLDER';
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS';